#
# Loosely based on https://github.com/intercept/intercept/blob/master/appveyor.yml
#
version: "{build}"

image: Visual Studio 2017

branches:
  only:
  - master

configuration:
- RelWithDebInfo

environment:
  matrix:
    - platform: Win32
      vcproj_dir: vcproj
      vcproj_file: vcproj\marpaESLIF.sln
      cmake_gen: "NMake Makefiles"
      cmake_args: ""

    - platform: x64
      vcproj_dir: vcproj64
      vcproj_file: vcproj64\marpaESLIF.sln
      cmake_gen: "NMake Makefiles"
      cmake_args: ""

matrix:
  fast_finish: true

before_build:
  - mkdir build
  - cd %vcproj_dir%
  - cmake .. -G "%cmake_gen%" %cmake_args%
  - cd ..

build:
  parallel: true
  verbosity: minimal

build_script:
  - cpan cpanminus
  - cpanm --notest Config::AutoConf::INI ExtUtils::CBuilder File::Basename File::Find File::Path
  - perl CMakeObjects.PL
  - del /f /s /q output
  - nmake check
  - nmake install
  - nmake package
