#
# Loosely based on https://github.com/intercept/intercept/blob/master/appveyor.yml
#
version: "{build}"

image: Visual Studio 2017

branches:
  only:
  - master

configuration:
- RelWithDebInfo

platform:
  - x86
  - x64

before_build:
  - cpan App::cpanminus
  - cpanm --notest Config::AutoConf::INI ExtUtils::CBuilder File::Basename File::Find File::Path
  - cd C:\projects\c-genericlogger
  - cmake -G "NMake Makefiles" .

build:
  parallel: true
  verbosity: minimal

build_script:
  - perl CMakeObjects.PL
  - del /f /s /q output
  - nmake check
  - nmake install
  - nmake package
