language: c
sudo: required
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
before_script:
  - sh ./install-c-genericLogger.sh
  - sh ./install-c-genericStack.sh
  - sh ./install-c-genericHash.sh
  - sh ./install-c-genericSparseArray.sh
  - cmake .
script:
  - make check
  - ./output/lib/marpaWrapperTester
  - ./output/lib/marpaWrapperAsfTester
  - ./output/lib/marpaWrapperAsfValueTester
  - ./output/lib/marpaWrapperAsfAmbiguousTester
  - ./output/lib/marpaWrapperTesterStatic
  - ./output/lib/marpaWrapperAsfTesterStatic
  - ./output/lib/marpaWrapperAsfValueTesterStatic
  - ./output/lib/marpaWrapperAsfAmbiguousTesterStatic
  - sudo make package
  - sudo make install
