language: c
sudo: required
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
before_script:
# We want to try perl standalone first
  - sudo apt-get update
  - sudo apt-get install cpanminus
  - sudo cpanm Config::AutoConf::INI ExtUtils::CBuilder File::Basename File::Find File::Path
  - perl CMakeObjects.PL
  - rm -rf output
  - sh ./install-c-genericLogger.sh
  - sh ./install-c-genericStack.sh
  - sh ./install-c-genericHash.sh
  - sh ./install-c-genericSparseArray.sh
  - cmake .
script:
  - make check
  - sudo make package
  - sudo make install
