language: c
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
before_script:
  - cmake .
script:
  - make check
  - sudo make package
  - sudo make install
