name: Unix

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,macos-latest]
        include:
          - os: ubuntu-latest
          - os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1

    - name: Perl pre-requesites
      run: |
        cpan App::cpanminus
        cpanm --notest Dist::Zilla
        cpanm --notest Config::AutoConf Config::AutoConf::INI Devel::GlobalDestruction Dist::Zilla Dist::Zilla::Plugin::Authority Dist::Zilla::Plugin::AutoMetaResources Dist::Zilla::Plugin::AutoPrereqs Dist::Zilla::Plugin::ChangelogFromGit::CPAN::Changes Dist::Zilla::Plugin::CPANFile Dist::Zilla::Plugin::DynamicPrereqs Dist::Zilla::Plugin::Encoding Dist::Zilla::Plugin::GatherDir Dist::Zilla::Plugin::GatherFile Dist::Zilla::Plugin::Git::Contributors Dist::Zilla::Plugin::Git::NextVersion Dist::Zilla::Plugin::GitHub::Meta Dist::Zilla::Plugin::MetaTests Dist::Zilla::Plugin::MinimumPerl Dist::Zilla::Plugin::MojibakeTests Dist::Zilla::Plugin::OurPkgVersion Dist::Zilla::Plugin::PodnameFromClassname Dist::Zilla::Plugin::PodWeaver Dist::Zilla::Plugin::Prereqs Dist::Zilla::Plugin::Prereqs::AuthorDeps Dist::Zilla::Plugin::PruneFiles Dist::Zilla::Plugin::Test::CPAN::Changes Dist::Zilla::Plugin::Test::CPAN::Meta::JSON Dist::Zilla::Plugin::Test::EOL Dist::Zilla::Plugin::Test::Kwalitee Dist::Zilla::Plugin::Test::MinimumVersion Dist::Zilla::Plugin::Test::NoTabs Dist::Zilla::Plugin::Test::Perl::Critic Dist::Zilla::Plugin::Test::Pod::Coverage::Configurable Dist::Zilla::Plugin::Test::Pod::LinkCheck Dist::Zilla::Plugin::Test::Portability Dist::Zilla::Plugin::Test::Synopsis Dist::Zilla::Plugin::Test::Version Dist::Zilla::PluginBundle::Starter::Git File::chdir File::Copy::Recursive File::Which JSON::MaybeXS Log::Any Log::Any::Adapter namespace::clean Pod::Coverage::TrustPod Pod::Weaver::PluginBundle::RJBS Safe::Isa Software::License::Perl_5 Test::CPAN::Changes Test::CPAN::Meta Test::CPAN::Meta::JSON Test::Deep Test::Deep::NoTest Test::EOL Test::Kwalitee Test::MinimumVersion Test::Mojibake Test::More::UTF8 Test::NoTabs Test::Perl::Critic Test::Pod Test::Pod::Coverage Test::Pod::LinkCheck Test::Portability::Files Test::Synopsis Test::Version Try::Tiny

    - name: Configure
      run: cmake -Wno-dev -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DTCONV_USE_ICU=NO -G "Unix Makefiles" .

    - name: Check
      run: make check VERBOSE=1

    - name: Look for dumps
      run: |
        find . -name "hs_err*log" -print -exec cat {} \;
        find . -name "core*" -print -exec sh -c 'gdb -c "{}" $(gdb -c "{}" -batch | grep -i "Core was generated by" | perl -ne "/\`([ a-zA-Z0-9_\/-]+)/ && print \"\$1\\n\"") -batch -ex "set pagination 0" -ex "thread apply all bt"' -- {} \;
