name: Unix

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,macos-latest]
        include:
          - os: ubuntu-latest
          - os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1

    - name: Perl pre-requesites
      run: |
        cpan App::cpanminus
        cpanm --notest Dist::Zilla
        pushd src/bindings/perl && dzil authordeps --missing | xargs cpanm --notest && popd
        pushd src/bindings/perl && dzil listdeps --develop --requires --omit-core `perl -e 'print "$]\n"'` --missing | xargs cpanm --notest && popd

    - name: Configure
      run: cmake -Wno-dev -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DTCONV_USE_ICU=NO -G "Unix Makefiles" .

    - name: Check
      run: make check VERBOSE=1

    - name: Look for dumps
      run: |
        find . -name "hs_err*log" -print -exec cat {} \;
        find . -name "core*" -print -exec sh -c 'gdb -c "{}" $(gdb -c "{}" -batch | grep -i "Core was generated by" | perl -ne "/\`([ a-zA-Z0-9_\/-]+)/ && print \"\$1\\n\"") -batch -ex "set pagination 0" -ex "thread apply all bt"' -- {} \;
